version: '3.8'
services:
  app:
    image: ${FRONTEND_IMAGE:-785874436221.dkr.ecr.us-east-1.amazonaws.com/ap-platform-frontend}:${FRONTEND_TAG:-latest}
    container_name: ap-dashboard-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    # Set additional environment variables in Portainer UI
