# Main docker-compose.yml for local development
# For production deployment, use individual stacks in infra/portainer-stacks/

version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    networks:
      - ap-platform-network
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next

  # Backend API service (to be implemented)
  # backend-api:
  #   build:
  #     context: .
  #     dockerfile: apps/backend-api/Dockerfile
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - ap-platform-network

  # Webhook service (to be implemented)
  # webhook-service:
  #   build:
  #     context: .
  #     dockerfile: apps/webhook-service/Dockerfile
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - ap-platform-network

networks:
  ap-platform-network:
    driver: bridge
