version: '3.8'

services:
  webhook-service:
    image: ${WEBHOOK_SERVICE_IMAGE:-785874436221.dkr.ecr.us-east-1.amazonaws.com/ap-platform-webhook-service}:${WEBHOOK_SERVICE_TAG:-latest}
    networks:
      - agent_network
      - traefik_public
    environment:
      - GO_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.webhook-service.rule=Host(`webhooks.agentpay.com.br`)
        - traefik.http.routers.webhook-service.entrypoints=websecure
        - traefik.http.routers.webhook-service.tls.certresolver=letsencrypt
        - traefik.http.services.webhook-service.loadbalancer.server.port=8081
        - traefik.docker.network=traefik_public
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agent_network:
    external: true
  traefik_public:
    external: true
