version: '3.8'

services:
  backend-api:
    image: ${BACKEND_API_IMAGE:-785874436221.dkr.ecr.us-east-1.amazonaws.com/ap-platform-backend-api}:${BACKEND_API_TAG:-latest}
    networks:
      - agent_network
      - traefik_public
    environment:
      - GO_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.backend-api.rule=Host(`api.agentpay.com.br`)
        - traefik.http.routers.backend-api.entrypoints=websecure
        - traefik.http.routers.backend-api.tls.certresolver=letsencrypt
        - traefik.http.services.backend-api.loadbalancer.server.port=8080
        - traefik.docker.network=traefik_public
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agent_network:
    external: true
  traefik_public:
    external: true
